### ISSUE TITLE
Update the procedure of verifying and creating collation

### ISSUE THREAD

**Issue by hwwhww** [ethereum/sharding#31]
##  Description
* For sharding validator, since we want to remove the `SHUFFLING_CYCLE` with stateless client, the syncing procedure would be executed more frequently with much lesser execution time.
* Verify the collation from the **guessing collation head**  and traceback the deeper collations round by round to get the head collation. In each round, pick collations with scores in range and verify them. Run as many rounds within a certain time.

##  Sub-tasks
- [x] Add `get_eligible_proposer` function in validator manager contract 
- [ ] Update validator manager contract after applying stateless client #28
- [ ] Implement GUESS_HEAD
- [ ] Implement UPDATE_WITNESS(tx, db)
- [ ] Implement CREATE_COLLATION(s, cb)

**Comment by hwwhww** [comment]
Close all old stuff
